include:
  - board: nice_nano_v2
    shield: first_left
    snippet: zmk-usb-logging
    artifact-name: first_left_debug

  - board: nice_nano_v2
    shield: first_right
    artifact-name: first_right

  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset
