include:
  - board: nice_nano_v2
    shield: first_left
    artifact-name: first_left

  - board: nice_nano_v2
    shield: first_right
    artifact-name: first_right

  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset
